version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    container_name: customers
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: customers
      POSTGRES_PASSWORD: customers
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql